### ISSUE TITLE
[BUG] Metadata url extraction from Confluence Document Loader

### ISSUE THREAD

**Issue by lde-net2** [FlowiseAI/Flowise#2052] opened 2024-03-27 11:27 UTC
**Describe the bug**
when extracting contents from a confluence page, the page url is saved as metadata.url instead of metadata.source into the database (pinecone here)
thus the "return source documents" in chats cannot return the correct link, and return a json popup instead, not really useful for end users

**To Reproduce**
1. import confluence data into pinecone using the confluence document uploader (split text on markdown)
2.  see that embeddings in pinecone have the page confluence url saved as metadata.url
3.  test a chat, with "return source documents" > will not output the correct pages links
4. in the database, rename some embedding field from "metdata.url" to "metadata.source"
5. the chat bot will now ouput the correct links for those embeddings

**Expected behavior**
the confluence document loaded should store pages urls as "metadata.source"

**Screenshots**

**Flow**

**Setup**
-   Flowise 1.6.2
-   OS,  Browser, Docker: not relevant

Thanks !

**Comment by HenryHengZJ** [comment] 2024-03-28 09:06
hey @lde-net2! langchain added as url - https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/web/confluence.ts#L228

**Comment by lde-net2** [comment] 2024-03-28 09:30
Thanks Henry
Sorry , i didn't catch it in Lanchain code.

can close this (not a bug) then

How would you suggest to handle this, as the chat module expects metadata.source ?

thanks !!

**Comment by mrkhachaturov** [comment] 2024-03-28 16:51
@lde-net2 
Can you share your chatflow?
I will try help you!

**Comment by lde-net2** [comment] 2024-03-28 22:42
i don't think this is related to the flow,  but instead a discrepedancy between the langchain metdata structure and what flowise expects.
i hacked the frontend chatmessage to use source.metada.url & source.metdadata.title instead of source.metadata.source
not clean..  but no way to get an advice or answer nowhere :( !

**Comment by toi500** [comment] 2024-03-28 23:40
I think there is something bugged on Pinecone's end.

I had a similar bug where Pinecone was hard tagging the metadata "text" even if you tagged as "url" or anything else.

https://github.com/HonzaTuron/pinecone/issues/4#issuecomment-2018436559

For 2 weeks we were working on this problem so we quit.

**Comment by lde-net2** [comment] 2024-03-29 00:12
no, as henry pointed out abovce, langchain is saving the page url as metadata.url
pinecone is just storing the data the way it receives it

**Comment by HenryHengZJ** [comment] 2024-03-30 13:12
you'll have to override the `ConfluencePagesLoader` `createDocumentFromPage` method to change the metadata, or you can submit a PR to langchainjs then we dont have to override in Flowise.

Since this is not a bug, I'll be closing it for now

**Closed by HenryHengZJ** 2024-03-30 13:12 UTC
