### ISSUE TITLE
Neo4J RETRIEVER Integration [FEATURE]

### ISSUE THREAD

**Issue by MarcellM01** [FlowiseAI/Flowise#1344] opened 2023-12-06 13:32 UTC
Integration of Neo4J retriever would be amazing to help create knowledge graph-based RAG-s.

https://python.langchain.com/docs/integrations/vectorstores/neo4jvector

**Comment by vinodkiran** [comment] 2023-12-08 03:53
Duplicate of [1237](https://github.com/FlowiseAI/Flowise/issues/1237)

**Closed** 2024-09-19 15:42 UTC
Labels: duplicate, enhancement
