### ISSUE TITLE
OpenAI  Model Name is empty

### ISSUE THREAD

**Issue by javawangzi** [FlowiseAI/Flowise#2554] opened 2024-06-02 10:13 UTC
After I drag OpenAI or OpenAI embeddings, Model Name is empty.

**Comment by danieldabate** [comment] 2024-06-02 20:54
Hi @javawangzi, could you provide clear steps on how to reproduce the issue? I can't reproduce it.

Also, please share more information about your setup, as this might be an issue specific to yours:
-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Comment by javawangzi** [comment] 2024-06-03 13:12
Hi Daniel

I base in China, and the screenshot like below.
![image](https://github.com/FlowiseAI/Flowise/assets/50722329/0ea6696d-31ef-4f76-8654-dac730877a91)

**Comment by javawangzi** [comment] 2024-06-03 22:44
Hi @danieldabate 
After install 1.8.1, it's OK now.
Thanks

**Comment by javawangzi** [comment] 2024-06-03 22:54
I want to confirm another thing, only support three models?

![image](https://github.com/FlowiseAI/Flowise/assets/50722329/202d889a-27aa-424b-8b0b-00947954687d)

**Comment by danieldabate** [comment] 2024-06-03 23:02
I think you are looking for the ChatOpenAI node, which supports all models (including GPT4o)

**Comment by javawangzi** [comment] 2024-06-03 23:06
Yeah, thank you very much!

**Comment by HenryHengZJ** [comment] 2024-06-04 01:17
thanks @danieldabate for helping! closing for now

**Closed by HenryHengZJ** 2024-06-04 01:17 UTC
